import pandas as pd
df = pd.read_csv("data/sales_data.csv")
print ("--------DATA SHAPE--------")
print (df.shape)
print ("--------COLUMNS NAMES--------")
print (df.columns)
print ("--------DATA TYPES--------")
print (df.dtypes)
print ("--------FIRST 5 ROWS--------")
print (df.head(5))
print ("--------LAST 5 ROWS--------")
print (df.tail(5))
print ("--------MISSING VALUES--------")
print (df.isnull().sum())
print ("--------SUMMARY STATISTICS--------")
print (df.describe())
print ("Duplicate rows")
print (df.duplicated().sum())
